### ISSUE TITLE
.Net Version Upgrade? (.NET Core 3.1 End of Support on 3. December 2022)

### ISSUE THREAD

**Issue by romibi** [romibi/Scrap-Packed-Explorer#15]
I feel like I just started this project a few months ago but already notice that .NET Core is nearing its End of Support.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

- How difficult would it be to upgrade to .NET 6?
- What benefits would that have?
- What drawbacks would that have?

**Comment by Strongleong** [comment]
Just tried to upgrade .NET locally. 
Difficulty: 0. Only changed one parameter in project settings (Target platform)
 Tests are passing, GUI is working.

**Comment by Strongleong** [comment]
Upgraded .NET Core from 3.1 to 6.0 #16

**Comment by romibi** [comment]
For the Record:
.NET 6 needs Visual Studio 2022
