### ISSUE TITLE
Unexpected behavior of UI on resizing file information display 

### ISSUE THREAD

**Issue by Strongleong** [romibi/Scrap-Packed-Explorer#19]
When resizing file information display to the left tree view and list view are slides to the right too fast.

### How to reproduce:
 * move cursor to the line between list view and file information display until left-right arrow appears
 * while holding left mouse button move cursor to the right

### What happens:
 * file information display shrinks to the left
 * file view and tree view are shrinks to the right too fast

### What should happen:
I am not sure what is intended behavior but there is my assumptions:
 * file information display shrinks to the left
 * file view and tree view are shrinks to the right with same speed as file information display    
 
or 
 * file information display shrinks to the left
 * file view grows to the left

**Comment by romibi** [comment]
what the heck? … lol … yea that's strange 😄

**Comment by romibi** [comment]
I'll close this once i tested it again

**Comment by romibi** [comment]
I seriously did not test this fixed issue for more than 1½ years?
