### ISSUE TITLE
CLI: Add flag to supress error messages for --searchString in list subcommand

### ISSUE THREAD

**Issue by Strongleong** [romibi/Scrap-Packed-Explorer#32]
If `list --searchString` did not found anything it will dump 

```console
Could not find anything by query <query> in <file>
```

It screws up scripting of ScrapPackedExplorer.

Also I think ScrapPackedExplorer in cases like this should return non-zero status code

**Comment by romibi** [comment]
True … the message should either
- go to stderr to be able to redirect it separatelty from normal output
- or be supressable by a flag
- or both.

Also I agree about the non-zero status code.
