### ISSUE TITLE
CLI: Arguments in camelCase vs hyphenated-arguments

### ISSUE THREAD

**Issue by romibi** [romibi/Scrap-Packed-Explorer#34]
From PR #33:

@Strongleong wrote:
> About camelCase I am not so sure. Having camelCase --flags is just do not clicks in my head, can't explain it better.

@romibi (me) answered
> I understand what you mean … true, hyphenated cli arguments are more common.
> But in #13 we switched the few cli arguments that were hyphenated to camelCase to match the others.
> Maybe we should have used hyphenated arguments instead?
>
> Should we change all arguments again?
> But as soon as someone starts to use it in their scripts we should try to avoid to change it anymore.
> What do you think?

So yea, camelCase vs hyphenated-arguments?

**Comment by Strongleong** [comment]
The argument is: I can't remember any CLI software that uses camelCase arguments. Devs are lazy and we don't wanna press shift key when we don't need it :)

**Comment by romibi** [comment]
arguments against changing: backwards compatibility to existing scripts …
I don't think there are many … so I think we can ignore that.

I'm fine with a PR … but I probably wont have time later today to merge another one.

**Comment by Strongleong** [comment]
I maybe gonna do it next week
