### ISSUE TITLE
Open file with ScrapPackedExplorer

### ISSUE THREAD

**Issue by romibi** [romibi/Scrap-Packed-Explorer#4]
I want to open .packed files directly with the ScrapPackedExplorer by double clicking them.

Missing: 
- [x] correct commandline parsing
- [ ] optionally register file extension (maybe)

**Comment by Strongleong** [comment]
- [X] correct commandline parsing

**Comment by romibi** [comment]
> * [x]  correct commandline parsing

And where is the change wo allow opening files in GUI by calling `ScrapPackedExplorer.exe Data.packed`

**Comment by romibi** [comment]
regarding "optionally register file extension (maybe)"
we don't have an installer and people can just select "always" when using "open with"
therefore i'll close this issue

**Comment by Strongleong** [comment]
I thought we will add a button somewhere that will register file extension.
Say, "Always open .packed files with ScrapPackedExplorer" in settings window or something like that
