### ISSUE TITLE
filter/search file or folder

### ISSUE THREAD

**Issue by romibi** [romibi/Scrap-Packed-Explorer#7]
- [x] the file list should just be filtered based on the search string
- [x] with regex off only support * (any amount of characters) and ? (one character) like in windows explorer
- [x] with regex on use proper regex (* and ? wildcards from windows explorer are not normal regex)
- [x] "starts with" or "includes"?
    maybe add an additional parameter to change that … but default = includes
- [x] maybe add an additional parameter to switch between "matching file name" and "matching whole path"
    filename => "file1.txt"
    filepath => "someFolder/file1.txt"

### Example:
**search for:** spaghetti
**files**
1) spaghetti.txt
2) spaghetti/file.txt
3) folder/spaghetti.txt

with "matching file name" and "includes" mode -> 1 & 3
with "matching file name" and "starts with" mode -> 1
**with "matching path" and "includes" mode -> all [Default]** 
with "matching path" and "starts with" mode -> 1 & 2

**Comment by Strongleong** [comment]
Done?

**Comment by romibi** [comment]
Works,
will be in next release.
